lib/libhdf5.a
lib/libhdf5_hl.a
lib/libhdf5_hl.la
lib/libhdf5_hl.so
lib/libhdf5_hl.so.10
lib/libhdf5_hl.so.10.0.2
lib/libhdf5.la
lib/libhdf5.settings
lib/libhdf5.so
lib/libhdf5.so.10
lib/libhdf5.so.10.1.0
lib/libnetcdf.a
lib/libnetcdff.a
lib/libnetcdff.la
lib/libnetcdff.so
lib/libnetcdff.so.6
lib/libnetcdff.so.6.0.1
lib/libnetcdf.la
lib/libnetcdf.settings
lib/libnetcdf.so
lib/libnetcdf.so.11
lib/libnetcdf.so.11.0.3

lib/pkgconfig:
netcdf-fortran.pc
netcdf.pc
